// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UsedCars.Data;

namespace UsedCars.Data.Migrations
{
    [DbContext(typeof(UsedCarsContext))]
    [Migration("20191201143002_CreateDatabase")]
    partial class CreateDatabase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.1");

            modelBuilder.Entity("UsedCars.Model.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Color")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("Price")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Cars");

                    b.HasData(
                        new
                        {
                            Id = 2,
                            Color = "zwart",
                            Name = "volvo",
                            Price = 28000,
                            Year = 2018
                        },
                        new
                        {
                            Id = 3,
                            Color = "grijs",
                            Name = "volvo",
                            Price = 25000,
                            Year = 2017
                        },
                        new
                        {
                            Id = 4,
                            Color = "grijs",
                            Name = "audi",
                            Price = 35000,
                            Year = 2017
                        },
                        new
                        {
                            Id = 5,
                            Color = "rood",
                            Name = "audi",
                            Price = 30000,
                            Year = 2015
                        },
                        new
                        {
                            Id = 6,
                            Color = "blauw",
                            Name = "renault",
                            Price = 18000,
                            Year = 2015
                        },
                        new
                        {
                            Id = 7,
                            Color = "blauw",
                            Name = "nissan",
                            Price = 21000,
                            Year = 2016
                        },
                        new
                        {
                            Id = 8,
                            Color = "groen",
                            Name = "vw",
                            Price = 15000,
                            Year = 2012
                        },
                        new
                        {
                            Id = 1,
                            Color = "rood",
                            Name = "volvoObj",
                            Price = 23000,
                            Year = 2017
                        },
                        new
                        {
                            Id = 9,
                            Color = "geel",
                            Name = "volvoObj2",
                            Price = 22000,
                            Year = 2017
                        },
                        new
                        {
                            Id = 10,
                            Color = "geel",
                            Name = "volvoObj3",
                            Price = 20000,
                            Year = 2011
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
